### ISSUE TITLE
ws / wss support

### ISSUE THREAD

**Issue by zielu** [hivemq/mqtt-cli#105]
## Problem or use case
Is there one already or are you planning to add ws / wss support ?

**Comment by gitseti** [comment]
Hi @zielu,

Unfortunately, there is no WebSockets support planned for upcoming releases.
However, I will add this as a feature request and evaluate it for upcoming releases.

**Comment by gitseti** [comment]
After a quick evaluation I think that I can add the WebSockets support in the next release.
Therefore, I will add this feature request to project of the next release. 👍 

Thanks for the request! :)
