### ISSUE TITLE
Refactor HiveMQ-MQTT-Client library to be usable with GraalVM

### ISSUE THREAD

**Issue by ahelmbr** [hivemq/mqtt-cli#11]
The current mqtt-client lib is not usable within graalVM native-image, 
because of reflection and dependenciy injection via guice and netty. 

Second problem is the usage of netty - initializer must be declared within the library.

- talk to @SgtSilvio when MQTT lib is available for this 

- make cli graalVM able
- add documentation for graalVM support

**Comment by sbaier1** [comment]
@gitseti just wondering why this was closed? is there a follow up ticket? AFAIK the current status is that the image is working (including jline), just need to test and add SSL support
