### ISSUE TITLE
Certificate Chain Validation

### ISSUE THREAD

**Issue by mathias-ewald** [hivemq/mqtt-cli#132]
## Expected behavior
Providing the full certificate chain (root and intermediate) via `--certfile ca.crt` mqtt should be able to verify the validity of the server certificate.

## Actual behavior
Mqtt outputs `unable to find valid certification path to requested target` even though openssl thinks it's valid:

`openssl verify -CAfile ca.crt mosquitto-server.crt`

### Steps
1. Configure Mosquitto with a Letsencrypt certificate created by issuer "=Digital Signature Trust Co., CN=DST Root CA X3"
2. Store the Letsencrypt CA and Root CA in a file ca.crt, `cat root.crt server.crt > ca.crt` - the order does not matter, I tried both
3. Run `mqtt pub -h FQDN -p 8883 -u USER -pw PASS --cafile ca.crt -t TOPIC -m MSG`

## Details
```
$ mqtt --version
1.1.1
Picocli 4.0.4
JVM: 13 (Oracle Corporation OpenJDK 64-Bit Server VM 13+33)
OS: Mac OS X 10.14.6 x86_64
```

**Comment by gitseti** [comment]
Thanks for the issue, @mathias-ewald!
I will look into this as soon as possible. 

For now, could you try the following?
```
mqtt pub -h FQDN -p 8883 -u USER -pw PASS --cafile root.crt --cafile server.crt -t TOPIC -m MSG
```

**Comment by jcassee** [comment]
I have the same problem. Passing `--cafile /etc/ssl/certs/ca-certificates.crt`, which contains all trusted CA's, does not work. Passing `--cafile intermediate.pem` does work. The server has supplies the intermediate certificate and other clients are able to validate the chain. Maybe mqtt-cli only validates one level deep?

**Comment by gitseti** [comment]
Sorry for the late answer. @jcassee. 
Yes, unfortunately the cli expects the cafile to only contain one certificate.

Nevertheless, it should be possible to pass in more certificates by specifying multiple ``--cafile`` options.

As soon as I have some spare time, I will work on this first! :)
