### ISSUE TITLE
Add command to test simple MQTT features of an MQTT broker

### ISSUE THREAD

**Issue by MicWalter** [hivemq/mqtt-cli#134]
## Problem or use case
It would be nice to have a tool that can be run against an MQTT broker and the tool will check what features are enabled and what limits the broker has.

For example running the command "mqtt test" would test the broker (default at localhost:1883) and print a summary of what MQTT features work and which don't.

Example output:
```
Result for broker 'localhost:1883':
MQTT 3: supported
MQTT 5: supported
Wildcard subscription: disabled
Retained messages: enabled
Maximum message size: 100.000 bytes
etc.
```

Of course port, host should be changeable:

mqtt test
-h [Optional; default: localhost]
-p [Optional; default: 1883]

**Comment by gitseti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [MQTT CLI 1.2.0](https://trello.com/c/HzYaZrXD/18-mqtt-cli-120)
