### ISSUE TITLE
Read message from file

### ISSUE THREAD

**Issue by davidlane-iteratec** [hivemq/mqtt-cli#146]
## Problem or use case
It is a pain and os dependent slurping in an mqtt message from a file into a var and using the var on the command line / shell.
## Preferred solution or suggestions
It would be very useful to either have 
- a different parameter to specify the name of a file to use
- or something like the curl syntax where starting the message with a @ indicates it is a filename

**Comment by sarenameas** [comment]
How did you slurp a file into a var to publish?

**Comment by davidlane-iteratec** [comment]
payload=$(<test.json)

mqtt pub ... -m "$payload" 

This can cause problems in Windows with large payloads.

**Comment by gitseti** [comment]
#272 
You can now use the `-m:file` option to read in the message from a specified file.
