### ISSUE TITLE
An "-of" specified file always saved in the directory where the mqtt-cli.exe is located [windows]

### ISSUE THREAD

**Issue by ayavilevich** [hivemq/mqtt-cli#163]
## Expected behavior
If running
``mqtt-cli.exe sub -t [x] -h [x] -u [x] -pw [x] -V 3 -of c:\temp\log.txt -T``
expecting the log to be in c:\temp\log.txt

## Actual behavior
instead the log is saved in C:\prog\mqtt-cli-4.4.0-win\log.txt where the exe is located.

### Steps
Download windows build zip.
Run ``mqtt-cli sub`` with ``-of`` that includes a full path of a file.

### Reproducer code
N/A

## Details
- Affected MQTT CLI version(s): 
- Used JVM version:

4.4.0
Picocli 4.5.0
JVM: 1.8.0_261 (Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 25.261-b12)
OS: Windows 10 10.0 amd64

**Comment by SgtSilvio** [comment]
Hi @ayavilevich 
Thank you for reporting this.
I will label this as a bug, but it will need further investigation.

In the meantime could you try the following paths for the parameter and comment if the problem still happens?
`-of "C:\temp\log.txt"`
`-of "C:/temp/log.txt"`
`-of "C:\\temp\\log.txt"`

**Comment by ayavilevich** [comment]
@SgtSilvio I tried the paths above and it didn't make a difference.

unable to find a combination that will cause it to follow the full path. :(

**Comment by gitseti** [comment]
Fixed by https://github.com/hivemq/mqtt-cli/pull/256
