### ISSUE TITLE
Client ID greater than 23 bytes not possible

### ISSUE THREAD

**Issue by ertanden** [hivemq/mqtt-cli#166]
## Expected behavior

As far as I know, since MQTT 3.1.1 the clients should not restrict the Client ID length. 

It is the brokers responsibility to check/enforce the length. If we have a broker that supports ClientID's greater than 23 bytes and we make use of long identifiers, then it's not possible to use MQTT-CLI with our broker.

## Actual behavior

The provided clientIDs (with -i) greater than 23 bytes are rejected by the client.

## Details
- Affected MQTT CLI version(s): 1.2.0
- Used JVM version: 11

**Comment by SgtSilvio** [comment]
Hi @ertanden 
You can use ids of arbitrary length.
I tried it with
`mqtt pub -h broker.hivemq.com -i 123456789012345678901234567890 -t test -m test`
and
`mqtt sub -h broker.hivemq.com -i 1234567890ß1234567890ß1234 -t test`

The CLI only logs a warning `Identifier '123456789012345678901234567890' may be too long (identifier length '30' exceeds 23)` but connecting, subscribing and publishing works. The warning may be unnecessary.

Can you please confirm that is also works on your side?

**Comment by ertanden** [comment]
@SgtSilvio thanks for the quick reply. 

Sorry, that may be my misunderstanding then because of the log message of `Identifier '123456789012345678901234567890' may be too long (identifier length '30' exceeds 23)`.

I couldn't connect, but that is probably another issue than the client id then.

**Comment by SgtSilvio** [comment]
@ertanden I will close this issue now and mark it as invalid.
If you have a different problem, do not hesitate to create a new issue.
