### ISSUE TITLE
Upgrading hivemq/mqtt-cli/mqtt-cli 4.4.2 -> 4.4.3 with brew fails on MacOS 11

### ISSUE THREAD

**Issue by boban74** [hivemq/mqtt-cli#174]
Upgrading mqtt-cli 4.4.2 to 4.4.3 fials using the brew upgrade command with:

## Actual behavior
Warning: Calling depends_on :java is deprecated! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the hivemq/mqtt-cli tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/hivemq/homebrew-mqtt-cli/mqtt-cli.rb:6

## Error
Error: Calling depends_on java: "1.8+" is disabled! Use depends_on "openjdk@11", depends_on "openjdk@8" or depends_on "openjdk" instead.

## Details
- Affected MQTT CLI version(s): 4.4.2
- Used JVM version: OpenJDK 11

**Comment by gitseti** [comment]
Hi @boban74,
Thanks for reporting and sorry for the inconvenience.

It seems that homebrew does not support the `depends_on :java => "1.8+"` check anymore for installing via the mqtt-cli tap under https://github.com/hivemq/homebrew-mqtt-cli/blob/master/mqtt-cli.rb . 
I will replace this check soon.

For now you can simply open a terminal and type `brew edit mqtt-cli` and remove the line with `depends_on :java => "1.8+"` in it.
