### ISSUE TITLE
-l option doesn't work for con/connect command

### ISSUE THREAD

**Issue by frankyfish** [hivemq/mqtt-cli#179]
## Expected behavior
When I execute `con -l` I am able to enable logging to `~./mqtt.cli/logs` as doc states here: https://hivemq.github.io/mqtt-cli/docs/subscribe#connect-options 
Also it looks like documentation has a typo in _Explanation_ section for -l parameter: Log to ~./mqtt.cli/logs -> Log to ~./mqtt-cli/logs 
## Actual behavior
Unable to enable logging, getting output:
```
mqtt> con -l
Unknown option: '-l'
Try 'help connect' for more information.
```
### Steps
1. Deploy local instance of mosquitto MQTT Broker: `docker run -it -p 1883:1883 -p 9001:9001 eclipse-mosquitto`
2. Execute: `mqtt shell`
3. Try to connect to local broker with either `connect -l` or `con -l`
## Details
- Affected MQTT CLI version(s): 4.4.3
- Used JVM version: OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

**Comment by frankyfish** [comment]
It looks like `-l` option is also missing for `sub` and `pub` commands. Though documentation doesn't mention this option as being available for them this PR https://github.com/hivemq/mqtt-cli/pull/154 states that logging was added for all mqtt commands.

**Comment by SgtSilvio** [comment]
Hi @frankyfish 
Sorry for the delayed response.
The `-l` parameter is only used by the following commands:
```
mqtt pub -l ...
mqtt sub -l ...
mqtt shell -l
```
Inside the MQTT shell you do not need to set the the log option, all commands use the log option you specified when opening the shell.

**Comment by SgtSilvio** [comment]
The behavior should be right, so I will close this issue now.
Please do not hesitate to comment if I misunderstood something.
