### ISSUE TITLE
Add possibility to send an empty payload

### ISSUE THREAD

**Issue by henriksvensson** [hivemq/mqtt-cli#188]
## Problem or use case
I'm using mqtt-cli to communicate with a device running the [Tasmota](https://github.com/arendst/tasmota/) firmware. One feature of Tasmota is the ability to request a status update by sending an empty message to a command topic, see [Tasmota MQTT documentation](https://tasmota.github.io/docs/Commands/#with-mqtt).

From what I understand of mqtt-cli, it is not possible to send and empty payload to a topic, though it seems supported by MQTT brokers. It would be great to be able to do this!

## Preferred solution or suggestions
Maybe the most straight-forward solution would be to let the `-m` parameter on the pub command be optional and send an empty payload if not set. Another option could be to add another parameter `--no-message` or similar to make it explicit that this is actually what the user wishes to do.

Thanks for a great tool!

**Comment by gitseti** [comment]
Hi @henriksvensson & thank you for your request.

Have you tried `mqtt pub -t topic -m "" -h <your-broker-address>`?

**Comment by henriksvensson** [comment]
Hi @gitseti and thanks for a quick reply! I did try it and failed yesterday, but when I ran it again just know it works as expected. My bad, PEBKAC =).

Thanks again for a great tool!
