### ISSUE TITLE
Can't connect to AWS IoT Core broker

### ISSUE THREAD

**Issue by aiden-francois** [hivemq/mqtt-cli#192]
I'm attempting to connect to an AWS IoT Core endpoint before evaluating using HiveMQ as MQTT client library in an Android app.
The purpose is testing and learning from mqtt-cli source how to use TLS auth via self-signed certificates within the HiveMQ client library.

Both MQTT Explorer and MQTTX can connect, subscribe and publish successfully to the broker with the same configuration (at least in my understanding)

I am not sure if it is related to #149 

## Expected behavior
Being able to connect to AWS IoT Core MQTT broker with TLS and self-signed certificates.

## Actual behavior
For mqtt shell connect
```
password can't be null
Timeout while waiting for CONNACK
```

For mqtt test
```
Could not build SSL config - password can't be null
```

### Steps

```
mqtt shell
connect -V 3 --host xxxxxv12345789-ats.iot.eu-north-1.amazonaws.com --port 8883 --cafile AmazonRootCA1.pem --cert xxx-certificate.pem.crt --key xxx-private.pem.key
```

or
```
mqtt test -V 3 --host xxxxxv12345789-ats.iot.eu-north-1.amazonaws.com --port 8883 --cafile AmazonRootCA1.pem --cert xxx-certificate.pem.crt --key xxx-private.pem.key
```

## Details
- Affected MQTT CLI version(s): 4.5.1
- Used JVM version:JVM: 1.8.0_181 (Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
- Operating System: macOS 10.14.6

**Comment by gitseti** [comment]
Hi @aiden-francois and thank you for your issue! :) 

I could trace this down as CLI-only bug - It should definetly work fine if you use the MQTT-Client-Library.


On to the actual bug for future reference:

If we build build the KeyStore for a Client in `SslOptions.java` `buildSslConfig`, we are not taking into consideration the full certificate chain because `FileToCertificateConverter` only returns the first certificate in the chain for now.

To fix this we would need to use bouncycastle `CertifcateFactory` in the `CertificateConverterUtils` class and return an array of certificates in the `FileToCertificateConverter`:
```java
org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory().engineGenerateCertificates(new FileInputStream(keyFile)).forEach()
```

`FileToCertifcateConverter` must then return the array of certifcates:
```java
public X509Certificate[] convert()
```

And in `SslOptions` the clientCertifate should now be an array of certifcates:
```
 private X509Certificate[] clientCertificates;
```

Now we can iterate over the whole certicate chain in `buildSslConfig`:
```java 
private KeyManagerFactory buildKeyManagerFactory(final @NotNull X509Certificate[] certs, final @NotNull PrivateKey key) throws KeyStoreException, CertificateException, NoSuchAlgorithmException, IOException, UnrecoverableKeyException {

        final KeyStore ks = KeyStore.getInstance(KeyStore.getDefaultType());

        ks.load(null, null);

        ks.setKeyEntry("mykey", key, null, certs);

        final KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());

        keyManagerFactory.init(ks, null);

        return keyManagerFactory;
    }
```

**Comment by aiden-francois** [comment]
Hi @gitseti, thanks for the quick investigation!

I rebuilt from the intermediate-certificates-are-ignored branch which includes #193 and it still fails although differently for shell connect.

* connect from the shell returns `Could not build SSL configuration` immediately instead of what was observed previously: `password can't be null` then `Timeout while waiting for CONNACK` after a delay.
* mqtt test fails the same with `Could not build SSL config - password can't be null`

Am I possibly using the wrong command line parameters?

**Comment by gitseti** [comment]
Hmm, could you also verify the problem for Java 11?

**Comment by aiden-francois** [comment]
Good catch @gitseti !
It's connecting just fine on shell and test on `OS: Mac OS X 10.14.6 x86_64` with
```
JVM: 11.0.2 (Oracle Corporation OpenJDK 64-Bit Server VM 11.0.2+9)
JVM: 13.0.1 (Oracle Corporation OpenJDK 64-Bit Server VM 13.0.1+9)
```
So the issue is specific to Mac OS current Oracle Java 1.8 runtime for this OS.

**Comment by gitseti** [comment]
My best guess  is that in Java 8 or less that one of those calls of `KeyStore` does not allow a password being null:

```java
ks.load(null, null);
ks.setKeyEntry("mykey", key, null, certs);
```

**Comment by aiden-francois** [comment]
I will test that specifically then, on the platform where it fails.

However just like you said, the MQTT-Client-Library connect just fine to AWS IoT Core MQTT broker (tested on Android API 29) once providing the desired TrustManagerFactory and KeyManagerFactory.
