### ISSUE TITLE
Error while running mqtt swarm on uBuntu 18.04

### ISSUE THREAD

**Issue by KunalGitRepo** [hivemq/mqtt-cli#233]
## Expected behavior
After running following command swarm scenario should get executed. 

> ./bin/mqtt swarm run start -f /root/Downloads/hivemq-4.6.1/tools/hivemq-swarm/scenario/scenario.xml 

## Actual behavior
However see actual output in file attached.
[output.zip](https://github.com/hivemq/mqtt-cli/files/6686975/output.zip)

Here as per output line "<meta http-equiv="X-UA-Compatible" content="IE=11">" swarm scenario is getting executed on IE11 browser. However this should get executed on default browser. (Firefox in this case). 

### Steps
Execute command below. 

> ./bin/mqtt swarm run start -f /root/Downloads/hivemq-4.6.1/tools/hivemq-swarm/scenario/scenario.xml

## Details
- Affected MQTT CLI version(s):  4.6.1
- Used JVM version: 11

> ./bin/mqtt -V
4.6.1
Picocli 4.6.1
JVM: 11.0.11 (Ubuntu OpenJDK 64-Bit Server VM 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OS: Linux 5.4.0-74-generic amd64

**Comment by SgtSilvio** [comment]
Hi @KunalGitRepo 
Sorry for the late response.
It seems that you tried to connect to the port of your HiveMQ Control Center and not to the REST API of Swarm.

**Comment by LukasHiveMQ** [comment]
I will close this issue for now. If the problem still persists please open up a new issue.
