### ISSUE TITLE
Use private key in DER format

### ISSUE THREAD

**Issue by pozzugno** [hivemq/mqtt-cli#281]
Is it possible to use private key files in DER format? I tried without success, I received the error:

`Invalid value for option '--key': cannot convert 'client_key_rsa.der' to PrivateKey (The private key could not be recognized.)`

**Comment by LukasBrand** [comment]
Hey @pozzugno, 
unfortunately DER is not trivial to implement with Bouncycastle at the moment. However, we support PKCS1 and PKCS8 for PEM decoded files. Depending on your configuration, you can use the `openssl pkcs8` or `openssl rsa` tool to convert the private keys. There are some examples inside the `src/systemTest/resources/tls/certificate-generator-tool.sh` file of how to use the commands.
