### ISSUE TITLE
Problems using secure connection

### ISSUE THREAD

**Issue by lardeh** [hivemq/mqtt-cli#283]
Hi.
We are tying to setup a one-way SSL connection. And have tried different settings, as such:
`mqtt pub -t 'MQTT/TEST2' -h thehostname -p 1234 -s true --cafile cabundle_der.pem --capath /path/to/folder/withcert -m 123`
We get the follwoing error:
`
Invalid value for option '--capath' (DIR): cannot convert ' /path/to/folder/withcert' to X509Certificate (The given directory does not contain any valid certificates)
Try 'mqtt pub --help' for more information.
`
We have tried without cafile and without capath, but get similar errors. 

We have tried using certificates that are DER and Base64 encoded. 

Are we doing anything wrong here?

**Comment by LukasBrand** [comment]
Hi @lardeh,

I have added system tests for your use case and could not reproduce the issue. Can you please try your issue with the latest version of the CLI.

Thank you!
