### ISSUE TITLE
Tests red, on local source code build

### ISSUE THREAD

**Issue by cgi-gerlando-caldara** [hivemq/mqtt-cli#314]
## Expected behavior
Source Code Build and Tests are Green.
To work on the project I want to make sure I have the right build environment.

Maybe causesd with unstable dependencies und unclean testing, or more detail dev environment setup.

## Actual behavior

**Windows 10 64:**
`C:\projects\mqtt-cli>gradlew clean build
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :generateHivemqOpenApi
> Task :generateSwarmOpenApi
> Task :compileJava
> Task :compileTestJava
> Task :test

DefaultCLIPropertiesTest > emptyPropertyFile() FAILED
    org.opentest4j.AssertionFailedError at DefaultCLIPropertiesTest.java:89

DefaultCLIPropertiesTest > noPropertyFile() FAILED
    org.opentest4j.AssertionFailedError at DefaultCLIPropertiesTest.java:70

208 tests completed, 2 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

BUILD FAILED in 1m 24s
18 actionable tasks: 18 executed`

**Ubuntu 20.04.5 LTS:**

`:~/IdeaProjects/mqtt-cli$ ./gradlew clean build
 
> Task :integrationTest
 
ExportClientsCommandIT > rate_limit() FAILED
    java.lang.IllegalStateException at DockerClientProviderStrategy.java:156
 
ExportClientsCommandIT > client_detail_1_success() FAILED
    java.lang.IllegalStateException at DockerClientProviderStrategy.java:114
 
ExportClientsCommandIT > connection_refused() FAILED
    java.lang.IllegalStateException at DockerClientProviderStrategy.java:114
 
ExportClientsCommandIT > csv_options() FAILED
    java.lang.IllegalStateException at DockerClientProviderStrategy.java:114
 
ExportClientsCommandIT > client_details_25_success() FAILED
    java.lang.IllegalStateException at DockerClientProviderStrategy.java:114
 
SwarmStatusCommandIT > getCommanderStatus() FAILED
    java.util.concurrent.ExecutionException at SwarmStatusCommandIT.java:87
        Caused by: java.lang.IllegalStateException at DockerClientProviderStrategy.java:114
 
SwarmRunStartCommandIT > startScenario() FAILED
    java.util.concurrent.ExecutionException at SwarmRunStartCommandIT.java:97
        Caused by: java.lang.IllegalStateException at DockerClientProviderStrategy.java:114
 
SwarmRunStopCommandIT > stopRun() FAILED
    java.util.concurrent.ExecutionException at SwarmRunStopCommandIT.java:92
        Caused by: java.lang.IllegalStateException at DockerClientProviderStrategy.java:114
 
Mqtt3FeatureTesterDefaultIT > initializationError FAILED
    java.lang.IllegalStateException at Mqtt3FeatureTesterDefaultIT.java:46
 
Mqtt3FeatureTesterQos0IT > initializationError FAILED
    java.lang.IllegalStateException at Mqtt3FeatureTesterQos0IT.java:42
 
Mqtt3FeatureTesterQos1IT > initializationError FAILED
    java.lang.IllegalStateException at Mqtt3FeatureTesterQos1IT.java:42
 
Mqtt3FeatureTesterRestrictedIT > initializationError FAILED
    java.lang.IllegalStateException at Mqtt3FeatureTesterRestrictedIT.java:41
 
Mqtt5FeatureTesterDefaultIT > initializationError FAILED
    java.lang.IllegalStateException at Mqtt5FeatureTesterDefaultIT.java:45
 
Mqtt5FeatureTesterQos0IT > initializationError FAILED
    java.lang.IllegalStateException at Mqtt5FeatureTesterQos0IT.java:42
 
Mqtt5FeatureTesterQos1IT > initializationError FAILED
    java.lang.IllegalStateException at Mqtt5FeatureTesterQos1IT.java:42
 
Mqtt5FeatureTesterRestrictedIT > initializationError FAILED
    java.lang.IllegalStateException at Mqtt5FeatureTesterRestrictedIT.java:41
 
26 tests completed, 16 failed, 10 skipped
 
> Task :integrationTest FAILED
 
FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':integrationTest'.
> There were failing tests. See the report at: file:///home/densanki/IdeaProjects/mqtt-cli/build/reports/tests/integrationTest/index.html
  
BUILD FAILED in 9s
19 actionable tasks: 11 executed, 7 from cache, 1 up-to-date`

### Steps
Git Version [78cd1c7](https://github.com/hivemq/mqtt-cli/commit/78cd1c7b14f61ad25efc9832031d6c740052ff7e)
gradle clean build

### Reproducer code
-

## Details
- Affected MQTT CLI version(s):  4.8.3
- Used JVM version: 
Windows:  openjdk version "1.8.0_322" OpenJDK Runtime Environment Corretto-8.322.06.1 (build 1.8.0_322-b06) OpenJDK 64-Bit Server VM Corretto-8.322.06.1 (build 25.322-b06, mixed mode)
Ubuntu: openjdk  version "1.8.0_322" OpenJDK Runtime Environment Corretto-8.322.06.1 (build 1.8.0_322-b06) OpenJDK 64-Bit Server VM Corretto-8.322.06.1 (build 25.322-b06, mixed mode)

**Comment by LukasHiveMQ** [comment]
Hello @cgi-gerlando-caldara,
sorry for the late response. I checked out the version you wrote and tried to reproduce your issue. It looks like you are missing a docker environment which is necessary to run the integration tests. 
The unit tests do also fail on my pc using windows but on mac and ubuntu they run just fine. Good catch! I will create a pull request in order to fix it.

**Comment by LukasHiveMQ** [comment]
I added the missing setup information in the README. 
Unfortunately, the current Windows and MacOs GitHub runners do not support some requirements to add test and setup automation for those platforms. As of now it needs to be tested manually.
