### ISSUE TITLE
Test Command: username/password from config.properties ignored

### ISSUE THREAD

**Issue by strowi** [hivemq/mqtt-cli#315]
## Expected behavior

`mqtt test` should succeed.

## Actual behavior

`mqtt test` fails with login error.

### Steps
create `$HOME/.mqtt-cli/config.properties`:
```
mqtt.host=xyz
mqtt.port=8883
mqtt.version=5
auth.username=emqx123
auth.password=password
```
And run:

```shell
~> mqtt test
MQTT 3: NOT_AUTHORIZED
MQTT 5: NOT_AUTHORIZED
```

while the following works:

```shell
~> mqtt test -u emqx123 -pw password
MQTT 3: OK
	- Maximum topic length: 4096 bytes
	- QoS 0: Received 10/10 publishes in 27,38ms
....
```

## Details
- Affected MQTT CLI version(s):  4.8.3, Picocli 4.6.2, JVM: 11.0.16 (Ubuntu OpenJDK 64-Bit Server VM 11.0.16+8-post-Ubuntu-0ubuntu122.04),OS: Linux 5.15.0-46-generic amd64

- Used JVM version: 11.0.16 (Ubuntu OpenJDK 64-Bit Server VM 11.0.16+8-post-Ubuntu-0ubuntu122.04)

**Comment by LukasHiveMQ** [comment]
Hi strowi, 
thank you for opening this issue. I had a look and could reproduce the problem. We forgot to set the default values for the authentication inside the test command. I will created a pull request with the code change and will add some system tests to verify the solution.
