### ISSUE TITLE
Print topic for incoming messages

### ISSUE THREAD

**Issue by hurenkam** [hivemq/mqtt-cli#325]
## Problem or use case
When monitoring multiple topics from the same instance, it is not clear on which
topic the message are coming in.
Especially when listening to multiple xxx/# topics, this makes it hard to see what exactly is happening.

## Preferred solution or suggestions
Would like to see a topic header printed just before the message itself is printed, perhaps enabled through a command line switch.

**Comment by LukasHiveMQ** [comment]
Hi @hurenkam, 
thanks for your request. Did you try to use the subscribe option `-T or --showTopics`?

For example:
```
mqtt sub -h broker.hivemq.com -t cli-show-topic/# -T
```
will result in:
```
cli-show-topic/test1: message1
```
if a publish is sent like this:
```
mqtt pub -h broker.hivemq.com -t cli-show-topic/test1 -m message1
```
The same functionality is also available inside the shell mode.
Does this resolve your issue?
