### ISSUE TITLE
Link points to the oldest version 

### ISSUE THREAD

**Issue by sanjmeh** [hivemq/mqtt-cli#327]
## Expected behavior
Should update to the latest version in any blog.

## Actual behavior
The blog link points to Version 1.0.0 

## To Reproduce
Go to [this blog](https://www.hivemq.com/blog/mqtt-cli/)

and follow steps to download the mqtt client.

## Details
The blog points to the version 1.0.0 while I came to know from the community that latest version is 4.9.1

**Comment by LukasHiveMQ** [comment]
Hello @sanjmeh,
I added the newest version of the cli as a parameter to the website. It should stay in sync with the latest release now.
