### ISSUE TITLE
Raspberry pi version, PLEASE!

### ISSUE THREAD

**Issue by trycoon** [hivemq/mqtt-cli#434]
## Problem or use case
Could you push a multi architecture to the Docker registry, so that we can debug MQTT on Raspberry pies to?

Today I get:
```
docker run -it hivemq/mqtt-cli shell
Unable to find image 'hivemq/mqtt-cli:latest' locally
latest: Pulling from hivemq/mqtt-cli
751ef25978b2: Pull complete 
140e22108c7d: Pull complete 
993077aca88e: Pull complete 
d1a940e1e4e8: Pull complete 
2bf15765a03c: Pull complete 
6ce07b04008d: Pull complete 
edfabf316879: Pull complete 
a0506348d9ef: Pull complete 
Digest: sha256:e822a48c7ba6cb86900f73bec0b5c8d0b9dde61c0d775d99a8a92b2e686a17a8
Status: Downloaded newer image for hivemq/mqtt-cli:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /usr/local/openjdk-11/bin/java: exec format error
```

## Preferred solution or suggestions
https://uninterrupted.tech/blog/creating-docker-images-that-can-run-on-different-platforms-including-raspberry-pi/
https://blog.while-true-do.io/podman-multi-arch-images/

**Comment by LukasBrand** [comment]
Hi @trycoon,
thanks for your feature request!

I will try to find time to add multi-arch support. In the meantime, you could use our Debian package as a direct install on the PI (assuming you have Raspbian / Raspberyy Pi OS installed).
see: https://hivemq.github.io/mqtt-cli/docs/installation/#debian-package

**Comment by LukasBrand** [comment]
https://hivemq.kanbanize.com/ctrl_board/22/cards/23983/details/

**Comment by LukasBrand** [comment]
Hi @trycoon,
I added support for the arm64v8 platform. The image will be published on our next release cycle.

Have a good day!
Lukas
