### ISSUE TITLE
Automatically generated client identifier consist of too many byte

### ISSUE THREAD

**Issue by gitseti** [hivemq/mqtt-cli#55]
In the Mqtt specification it is stated that a broker _"MUST allow ClientID’s which are between 1 and 23 UTF-8 encoded bytes"_.

Also _"The Server MAY allow ClientID’s that contain more than 23 encoded bytes"_

To support any broker the client identifier should always be generated so that it bytes do not exceed 23 in length.

**Currently** the cli generates a 54-byte string, e. g:
`hmqClientMQTT_5_0-74eca7ba-5bfe-410a-a724-b956011ef66f`

The **createIdentifier** method in ConnectCommand should be changed so that a 23-byte string is created as an unique identifier.

Also the broker must only accept the following characters in the identfier `"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"`. Therefore also the creation has to be changed so that only these characters are used.

http://docs.oasis-open.org/mqtt/mqtt/v5.0/cs02/mqtt-v5.0-cs02.html#_Toc514345331

**Comment by ahelmbr** [comment]
Change the creation that we have 
* at least an 8 Character long random Identifier by default that is extracted from the following chars:
"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".  
* the length 8 is configured by default - and can be changed if somebody likes to have more!

Additional if -i is used, 
* we should check against the corresponding regex.
